"""GRM-C3 author CPU baseline, not blind verification.

Prior art: DET1/SC2 (2026) strict threshold crossing; hand-computed
confusion tables are classical classification validation. External lead:
Chow 1970 reject decisions. New tests target this campaign's frozen seams.
"""
import copy
import math
from pathlib import Path

import pytest

from scripts import grm_c3 as c3
from scripts.grm_c3_register import digest


@pytest.fixture
def reg():
    return c3.registration()


def test_frozen_fixtures(reg):
    assert c3.fixture_gate(reg)["passed"]
    assert len(reg["cells"]) == 12
    by_id = {c["id"]: c for c in reg["cases"]}
    for cell in reg["cells"]:
        assert {by_id[i]["class"] for i in cell["case_ids"]} == {"correct", "decoy", "unavailable", "weak"}


def fires(masses, mounted, reg):
    return {k: v["fire"] for k, v in c3.decisions(masses, mounted, reg["rules"]).items()}


def test_hand_computed_trace_table(reg):
    # These expected bits are literal hand calculations, NOT generated by
    # the code under test: min .32 separates carried/candidate, .30 separates
    # candidate/near-zero, tiny nonempty separates near-zero/empty-band.
    samples = [([.7, .4], 12, [False, False, False, False]),
               ([.6, .32], 12, [True, False, False, False]),
               ([.4, .30], 12, [True, True, False, False]),
               ([.5, 1e-9], 12, [True, True, True, False]),
               ([0., 0.], 0, [True, True, True, True]),
               ([0.], 12, [True, True, True, False])]
    for masses, mounted, expected in samples:
        got = c3.decisions(masses, mounted, reg["rules"])
        assert [got[n]["fire"] for n in ["carried", "candidate", "near_zero", "empty_band"]] == expected
    assert c3.decisions([.6, .32, .1], 12, reg["rules"])["carried"]["first_index"] == 1
    assert c3.decisions([.6, .32, .1], 12, reg["rules"])["candidate"]["first_index"] == 2


@pytest.mark.parametrize("rule", ["carried", "candidate", "near_zero"])
def test_strict_exact_boundary(reg, rule):
    t = reg["rules"][rule]["threshold"]
    assert not c3.decisions([t], 12, reg["rules"])[rule]["fire"]
    assert c3.decisions([math.nextafter(t, 0.)], 12, reg["rules"])[rule]["fire"]
    assert not c3.decisions([math.nextafter(t, 1.)], 12, reg["rules"])[rule]["fire"]


@pytest.mark.parametrize("masses,mounted", [([], 0), ([float("nan")], 1),
    ([float("inf")], 1), ([-.1], 1), ([1.1], 1), ([.2], 0), ([0.], -1),
    ([0.], .5), ([False], 1), ([0.], True)])
def test_malformed_trace_rejected(reg, masses, mounted):
    with pytest.raises(ValueError):
        c3.decisions(masses, mounted, reg["rules"])


def row(c, mass, correct=False):
    return {"id": c["id"], "answer": "test only", "answer_correct": correct,
            "qualification_pass": True, "mounted_token_count": 0 if c["class"] == "unavailable" else 12,
            "signals": {"tokens": [{"ngh": {"mounted_mass": mass}}]}}


def test_hand_computed_confusion_table(reg):
    rows = [row(c, {"correct": .4, "weak": .32, "decoy": .30, "unavailable": 0.}[c["class"]],
                c["class"] in {"correct", "weak"}) for c in reg["cases"]]
    got = c3.metrics(rows, reg)
    expected = {"carried": [24, 12, 12, 0, 12], "candidate": [24, 0, 24, 0, 0],
                "near_zero": [12, 0, 24, 12, 0], "empty_band": [12, 0, 24, 12, 0]}
    for name, values in expected.items():
        assert [got["rules"][name][k] for k in ["TP", "FP", "TN", "FN", "correct_answers_at_risk"]] == values
        assert got["rules"][name]["lost_correct_answers"] is None
    assert got["rules"]["candidate"]["conservative_offline_eligible"]
    assert len(got["separating_cases"]) == 24
    assert len(got["prediction_evidence"]["weak_avoidable_carried_fires"]) == 12
    assert len(got["prediction_evidence"]["near_zero_nonempty_decoy_misses"]) == 12


@pytest.mark.parametrize("tp,fp,passed", [(22, 1, True), (21, 1, False), (22, 2, False), (24, 0, True)])
def test_integer_bars(reg, tp, fp, passed):
    rows = []
    positive = negative = 0
    for case in reg["cases"]:
        if case["class"] == "unavailable":
            mass = 0.
        elif case["class"] == "decoy":
            mass = .1 if positive < tp - 12 else .9
            positive += 1
        else:
            mass = .1 if negative < fp else .9
            negative += 1
        rows.append(row(case, mass))
    assert c3.metrics(rows, reg)["rules"]["candidate"]["detection_bar_pass"] is passed


def test_correct_miss_answers_are_also_at_risk(reg):
    rows = [row(c, 0. if c["class"] in {"decoy", "unavailable"} else .9,
                correct=True) for c in reg["cases"]]
    got = c3.metrics(rows, reg)["rules"]["candidate"]
    assert got["correct_answers_at_risk"] == 24
    assert not got["conservative_offline_eligible"]


@pytest.mark.parametrize("change", ["missing", "duplicate", "bad_bool", "qualification"])
def test_incomplete_or_failed_population(reg, change):
    rows = [row(c, 0. if c["class"] == "unavailable" else .5) for c in reg["cases"]]
    if change == "missing":
        rows.pop()
    elif change == "duplicate":
        rows[-1] = rows[0]
    elif change == "bad_bool":
        rows[0]["answer_correct"] = "false"
    else:
        rows[0]["qualification_pass"] = False
        assert c3.metrics(rows, reg)["qualification_failures"] == [rows[0]["id"]]
        return
    with pytest.raises(ValueError):
        c3.metrics(rows, reg)


def test_one_attempt_adapter_resets_and_never_retries():
    events = []

    class Arena:
        stop_sequences = ["STOP"]

        def reset_live_cache(self):
            events.append("reset")

        def _attempt(self, question, picks, ngen, deposit, stops, defer_memory):
            events.append((question, picks, ngen, deposit, stops, defer_memory))
            return "answer", {}

    class Observer:
        def __init__(self, arena, aliases, ngen, active_detectors):
            assert aliases == {3}
            assert active_detectors == {"D-NGH"}
            events.append("observer")

        def __enter__(self):
            return self

        def __exit__(self, *args):
            events.append("observer_closed")

        def finish(self):
            return {"test_only": True}

    assert c3.observe_attempt(Arena(), {"question": "Q"}, [3], Observer, 32) == ("answer", {"test_only": True})
    assert events == ["reset", "observer", ("Q", [3], 32, False, ["STOP"], True), "observer_closed"]


def test_fixture_tamper_not_hidden_by_rehash(reg):
    bad = copy.deepcopy(reg)
    c = next(c for c in bad["cases"] if c["class"] == "decoy")
    c["nodes"][0]["text"] += " " + c["expected_values"][0]
    c["sha256"] = digest({k: v for k, v in c.items() if k != "sha256"})
    bad["case_set_sha256"] = digest(bad["cases"])
    with pytest.raises(ValueError, match="target presence mismatch"):
        c3.fixture_gate(bad)


def test_registration_exclusive_writer(tmp_path):
    path = tmp_path / "immutable.json"
    c3.write(path, {"a": 1})
    with pytest.raises(FileExistsError):
        c3.write(path, {"a": 2})


def test_actual_imported_helpers_are_reused():
    # Source contract only; this does not claim any GPU path was executed.
    source = Path(c3.__file__).read_text()
    assert "workers.campaign._answer_correct(answer, c)" in source
    assert "_install_lived_nodes(repo, e2e, c)" in source
    assert "sc2._first_below(masses, rule[\"threshold\"])" in source
    assert "sc12.min_mounted_mass(row)" in source
